### ISSUE TITLE
Zviditeľniť články a blogy

### ISSUE THREAD

**Issue by bedna-KU** [mireq/Shakal-NG#18]
Dávnejšie sme preberali neviditeľnosť blogov a článkov na hlavnej strane. Ty si mi ukazoval aj nejaký návrh, že názvy boli hore nad fórom, pamätáš mama?

**Comment by mireq** [comment]
Nespomínam, akurát je momentálne zoznam blogov v bloku s fórom na
http://new.linuxos.sk/
Dňa 13.10.2015 10:28 používateľ "Mario" <notifications@github.com> napísal:

**Comment by bedna-KU** [comment]
Neviem či ten screenshot mám doma odložený, skúsim potom pohľadať.

Inak čo hovoríš na to keby text **::Najnovšie komentáre::** išiel namiesto textu **Predmet**
Takto isto to spraviť s ::Nediskutované témy::, ::Najdiskutovanejšie témy::, ::Najnovšie blogy::.

Osobne by som hodil nadpis **Diskusné fórum** za "Domček" a týmito úpravami by sme získali dosť miesta na stránke.

**Comment by mireq** [comment]
Skús pohľadať lebo moja hlava prepitá už toho moc nepamätá. Keď niečo môžeš uploadnuť aj rovno sem (ono to podporuje drag & drop) nech to dade nestratím.

To diskusné fórum by som za domček nedával, možno by som radšej skryl navigáciu na home stránke. So zvyškom môžem súhlasiť.

**Comment by bedna-KU** [comment]
Nemám to, na spoň som si po čase upratal pár mega. Zajtra navečer to nakreslím cca ako to bolo a pastnem sem.

**Comment by bedna-KU** [comment]
1. Názvy článkov a blogov nad fórom

![los1](https://cloud.githubusercontent.com/assets/4377084/11164666/0e9dc4e4-8af7-11e5-88b2-d03d636720bb.jpg)

2, Upozornenie na nový článok, alebo blog v červenej bublinke

![los2](https://cloud.githubusercontent.com/assets/4377084/11164672/3623dcce-8af7-11e5-8f2a-e9741d805d0d.jpg)

3. Zamiešať články a blogy do fóra

![los3](https://cloud.githubusercontent.com/assets/4377084/11164676/4cbbf4ee-8af7-11e5-8671-cf8f14cbbfab.jpg)
