### ISSUE TITLE
Pri použití https nefunguje editor

### ISSUE THREAD

**Issue by SGOrava** [mireq/Shakal-NG#43]
Pokiaľ pristupujem na stránku cez https tak nefunguje ani jeden textový editor...
presnejšie sa nezobrazuj=u žiadne tlačítka, je tam len prázdne pole na písanie textu...

**Comment by mireq** [comment]
Ctrl+F5, nie je to problém s https, ale browser cachuje starý editor a ten nemá kam nalepiť.

**Comment by SGOrava** [comment]
Ďakujem, už to funguje :)
