### ISSUE TITLE
Blogy - Súbor nebol nájdený

### ISSUE THREAD

**Issue by SGOrava** [mireq/Shakal-NG#47]
Keď chcem zobraziť nejaký blog tak mi vypíše **Súbor nebol nájdený**

**Comment by mireq** [comment]
Kde konkrétne? Nech to preklikávam akokoľvek blogy mi zobrazuje.

**Comment by SGOrava** [comment]
https://linuxos.sk/blog/mirecove-dristy/detail/linuxos-novinky-50-tyzden-2015/

http://i.imgur.com/3VdvksK.png

**Comment by mireq** [comment]
To je minimálne divné, mne to funguje v pohode.

![blog](https://cloud.githubusercontent.com/assets/33599/11934050/e9bcb20e-a7ff-11e5-9f01-47817b12ea3f.png)

**Comment by SGOrava** [comment]
keď som vymazal všetky cookies (odhlásilo ma to) tak sa mi to zobrazí...
ale keď sa opäť prihlásim tak mi znovu zobrazí tú chybu

**Comment by mireq** [comment]
Malo by to byť opravené

**Comment by SGOrava** [comment]
Ďakujem, už to ide :)
